server:
  port: 8889
spring:
  application:
    name: booking
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/pnrDB}

springdoc:
  api-docs:
    path: /v3/api-docs    # default; change only if you need
  swagger-ui:
    path: /swagger-ui     # final UI will be at /swagger-ui/index.html