server:
  port: 8888
spring:
  application:
    name: booking
  data:
    mongodb:
      uri: mongodb://localhost:27017/pnrDB?retryWrites=false

springdoc:
  api-docs:
    path: /v3/api-docs    # default; change only if you need
  swagger-ui:
    path: /swagger-ui     # final UI will be at /swagger-ui/index.html